info:
  tags:
    environment: ${spring.profiles.active}
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
# feign\u914D\u7F6E
feign:
  hystrix:
    enabled: true
# hystrix\u914D\u7F6E
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            # \u8D85\u65F6\u9650\u5236
            timeoutInMilliseconds: 70000

spring:
  #连接数据库配置 数据库用户名 数据库密码 数据库地址/数据库名
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/elp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: szzii.com:9092
    consumer:
      bootstrap-servers: szzii.com:9092
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        batch-size: 65536
        buffer-memory: 524288
  jackson:
    serialization:
      write-dates-as-timestamps: true
  rabbitmq:
    host: localhost
    port: 15672
    username: newadmin
    password: newpassword

#mappersql查询地址  对应实体类
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot.aop

#关闭自动转换驼峰命名规则
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false